name: Metrics • Languages
on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: alex4923
          template: classic
          base: ""                               
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          filename: metrics-langs.svg           
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics (langs)"
