name: Metrics • Header
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: alex4923
          template: classic
          base: header
          config_timezone: Europe/Brussels

          filename: metrics-header.svg        
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics (header)"
