name: GitHub Metrics
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  header:
    runs-on: ubuntu-latest
    steps:
      - name: Header only (stats privées incluses)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: alex4923
          template: classic
          base: header
          config_timezone: Europe/Brussels
          filename: metrics-header.svg
          committer_branch: main
          committer_message: "chore: update metrics (header)"

  languages:
    runs-on: ubuntu-latest
    steps:
      - name: Languages only (barres propres)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: alex4923
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          filename: metrics-langs.svg
          committer_branch: main
          committer_message: "chore: update metrics (langs)"
