name: GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *"   # 2x par jour
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alex4923
          template: classic
          base: header, activity
          config_timezone: Europe/Brussels
          repositories_affiliations: owner, collaborator, organization_member
          repositories: 200
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          filename: github-metrics.svg
